### ISSUE TITLE
У этих двух тестов одинаковое название - они тестируют одно и то же?

### ISSUE THREAD

**Issue by coursar** [Aljasones/TaxiService#2]
https://github.com/Aljasones/TaxiService/blob/51009808bfc591da72213698f281eef32545850a/src/test/java/ru/itpark/TaxiServiceTest.java#L7-L22

**Comment by coursar** [comment]
Если нет - надо отразить в названии

**Comment by Aljasones** [comment]
Один WithoutDiscount, другой WithDiscount, один тестирует сумму, когда еще не набирается скидка, другой тестирует, когда есть скидка, но она еще не дошла до максимального значения

**Comment by coursar** [comment]
Ок, не заметил, извиняюсь ))
